### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [PrelogSasa/Trees-smallest-ABC#1]
@PrelogSasa, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Trees-smallest-ABC`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

Mimogrede, priporočam, da pri delu v CoCalc namesto *Sage worksheet* uporabita tip datoteke *Jupyter Notebook*. Tako bosta imela boljšo kontrolo nad izvajanjem kode (lahko namreč eksplicitno organizirata kodo v celice), poleg tega pa je mogoče take datoteke prenesti in izvajati tudi lokalno (oziroma jih pregledovati, ko so naložene na GitHub).

**Comment by PrelogSasa** [comment]
Hvala za nasvete.
